// Shared data shapes for the EIP Impact Tracker.
// The matrix.json file (generated by scripts/sync.ts) conforms to `MatrixData`.

export type ImpactLevel = 0 | 1 | 2 | 3; // none | low | medium | high

export const IMPACT_LABELS: Record<ImpactLevel, string> = {
  0: "None",
  1: "Low",
  2: "Medium",
  3: "High",
};

/** A tech-stack audience — one column of the impact matrix. */
export interface StackCategory {
  id: string;
  label: string;
  blurb: string;
}

/** The fixed set of tech-stack audiences we score every EIP against. */
export const STACK_CATEGORIES: StackCategory[] = [
  { id: "wallet", label: "Wallet", blurb: "Wallets & signing UX (MetaMask, Rabby, smart accounts)" },
  { id: "l2", label: "L2 / Rollup", blurb: "Rollups & data-availability consumers" },
  { id: "node", label: "Node / Client", blurb: "Execution & consensus client implementers" },
  { id: "rpc", label: "RPC Provider", blurb: "RPC & API infra (Infura, Alchemy, self-hosted)" },
  { id: "indexer", label: "Indexer / Data", blurb: "Indexers, explorers & analytics (The Graph, Etherscan)" },
  { id: "contracts", label: "Contract Dev", blurb: "Smart-contract & tooling developers (Solidity, Foundry)" },
  { id: "staking", label: "Staking / Validator", blurb: "Validators, staking pools & node operators" },
];

export interface Eip {
  number: number;
  title: string;
  description: string;
  /** Standards Track | Meta | Informational */
  type: string;
  /** Core | Networking | Interface | ERC (for Standards Track) */
  category: string | null;
  status: string;
  url: string;
  /** impact level keyed by StackCategory.id */
  impact: Record<string, ImpactLevel>;
  /** short per-category rationale strings, keyed by StackCategory.id */
  why: Record<string, string>;
}

export interface Upgrade {
  /** human name, e.g. "Pectra" */
  name: string;
  /** the Hardfork Meta EIP number, e.g. 7600 */
  metaEip: number;
  status: string;
  /** Mainnet activation unix timestamp, if known */
  activatedAt: number | null;
  /** EIP numbers included in this upgrade */
  eips: number[];
}

export interface MatrixData {
  generatedAt: string;
  categories: StackCategory[];
  upgrades: Upgrade[];
  eips: Record<string, Eip>; // keyed by EIP number (as string)
}
